// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GreenlightContext))]
    [Migration("20260412151059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Backend.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCauseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubprocessRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubprocessRunId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Backend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InScope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Backend.Models.LocationStepRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredStepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubprocessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubprocessId");

                    b.HasIndex("LocationId", "SubprocessId", "RequiredStepName")
                        .IsUnique();

                    b.ToTable("LocationStepRegistry");
                });

            modelBuilder.Entity("Backend.Models.McpRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EomDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportMonth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportMonth")
                        .IsUnique();

                    b.ToTable("McpRuns");
                });

            modelBuilder.Entity("Backend.Models.ProcessLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("E2ERuntimeHours")
                        .HasColumnType("REAL");

                    b.Property<double>("EfficientRuntimeHours")
                        .HasColumnType("REAL");

                    b.Property<string>("EndMarker")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<double>("FailedRuntimeHours")
                        .HasColumnType("REAL");

                    b.Property<double>("InefficientRuntimeHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Iteration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextStarted")
                        .HasColumnType("TEXT");

                    b.Property<double>("OpportunityCostHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartMarker")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalRuntimeHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("McpRunId", "LocationId", "ScriptName", "StepName", "Iteration");

                    b.ToTable("ProcessLogEntries");
                });

            modelBuilder.Entity("Backend.Models.ScriptMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawScriptPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubprocessId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubprocessId");

                    b.HasIndex("LocationId", "RawScriptPattern")
                        .IsUnique();

                    b.ToTable("ScriptMappings");
                });

            modelBuilder.Entity("Backend.Models.SlaTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SlaDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubprocessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Workday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubprocessId");

                    b.HasIndex("LocationId", "SubprocessId")
                        .IsUnique();

                    b.ToTable("SlaTargets");
                });

            modelBuilder.Entity("Backend.Models.Subprocess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subprocesses");
                });

            modelBuilder.Entity("Backend.Models.SubprocessRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedSteps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ElapsedMinutes")
                        .HasColumnType("REAL");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubprocessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRequiredSteps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SubprocessId");

                    b.HasIndex("McpRunId", "LocationId", "SubprocessId")
                        .IsUnique();

                    b.ToTable("SubprocessRuns");
                });

            modelBuilder.Entity("Backend.Models.Issue", b =>
                {
                    b.HasOne("Backend.Models.SubprocessRun", "SubprocessRun")
                        .WithMany()
                        .HasForeignKey("SubprocessRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubprocessRun");
                });

            modelBuilder.Entity("Backend.Models.LocationStepRegistry", b =>
                {
                    b.HasOne("Backend.Models.Location", "Location")
                        .WithMany("StepRegistry")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Subprocess", "Subprocess")
                        .WithMany("StepRegistry")
                        .HasForeignKey("SubprocessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Subprocess");
                });

            modelBuilder.Entity("Backend.Models.ProcessLogEntry", b =>
                {
                    b.HasOne("Backend.Models.Location", "Location")
                        .WithMany("LogEntries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.McpRun", "McpRun")
                        .WithMany("LogEntries")
                        .HasForeignKey("McpRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("McpRun");
                });

            modelBuilder.Entity("Backend.Models.ScriptMapping", b =>
                {
                    b.HasOne("Backend.Models.Location", "Location")
                        .WithMany("ScriptMappings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Subprocess", "Subprocess")
                        .WithMany("ScriptMappings")
                        .HasForeignKey("SubprocessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Subprocess");
                });

            modelBuilder.Entity("Backend.Models.SlaTarget", b =>
                {
                    b.HasOne("Backend.Models.Location", "Location")
                        .WithMany("SlaTargets")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Subprocess", "Subprocess")
                        .WithMany("SlaTargets")
                        .HasForeignKey("SubprocessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Subprocess");
                });

            modelBuilder.Entity("Backend.Models.SubprocessRun", b =>
                {
                    b.HasOne("Backend.Models.Location", "Location")
                        .WithMany("SubprocessRuns")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.McpRun", "McpRun")
                        .WithMany("SubprocessRuns")
                        .HasForeignKey("McpRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Subprocess", "Subprocess")
                        .WithMany("SubprocessRuns")
                        .HasForeignKey("SubprocessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("McpRun");

                    b.Navigation("Subprocess");
                });

            modelBuilder.Entity("Backend.Models.Location", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("ScriptMappings");

                    b.Navigation("SlaTargets");

                    b.Navigation("StepRegistry");

                    b.Navigation("SubprocessRuns");
                });

            modelBuilder.Entity("Backend.Models.McpRun", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("SubprocessRuns");
                });

            modelBuilder.Entity("Backend.Models.Subprocess", b =>
                {
                    b.Navigation("ScriptMappings");

                    b.Navigation("SlaTargets");

                    b.Navigation("StepRegistry");

                    b.Navigation("SubprocessRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
