using System.Text.Json;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace Backend.Data;

/// <summary>
/// Seeds the DB from JSON artifacts generated by docs/seed-data/build-final-mapping.js (v6).
/// Source of truth:
///   - golden-mapping.json — per (location, subprocess): phase, scope, quarterly, mandatory steps
///   - log-entries.json   — 4 months of ProcessLogEntry rows, runtime fields pre-computed
///   - sla-targets.json   — SLA deadlines per location × subprocess
/// </summary>
public static class SeedData
{
    private const string ExpectedMappingVersion = "v6";

    // Location code → friendly name + region
    private static readonly Dictionary<string, (string Name, string Region)> LocationInfo = new()
    {
        ["AUDB"] = ("Australia", "APAC"),
        ["BEDB"] = ("Belgium Direct", "Europe"),
        ["BEGT"] = ("Belgium Group Treasury", "Europe"),
        ["DEDB"] = ("Germany Direct", "Europe"),
        ["DEGT"] = ("Germany Group Treasury", "Europe"),
        ["ESDB"] = ("Spain", "Europe"),
        ["FRDB"] = ("France", "Europe"),
        ["ICDB"] = ("ICG (International)", "Global"),
        ["ITDB"] = ("Italy", "Europe"),
        ["LUDB"] = ("Luxembourg", "Europe"),
        ["NLBTR"] = ("Netherlands BTR", "Europe"),
        ["NLRB"] = ("Netherlands Retail", "Europe"),
        ["PLDB"] = ("Poland", "Europe"),
        ["RODB"] = ("Romania", "Europe"),
        ["TRDB"] = ("Turkey", "Europe"),
        ["WBUS"] = ("Wholesale Banking US", "Americas"),
    };

    public static async Task InitializeAsync(GreenlightContext db)
    {
        // Skip if already seeded
        if (await db.Locations.AnyAsync()) return;

        Console.WriteLine("Seeding database (v6 golden mapping)...");

        var basePath = Path.Combine(AppContext.BaseDirectory, "Data", "SeedData");

        // ---- 1. Locations ----
        var locations = new Dictionary<string, Location>();
        foreach (var (code, (name, region)) in LocationInfo)
        {
            var inScope = code != "ICDB"; // ICDB is adhoc per v6 mapping
            var loc = new Location { Code = code, Name = name, Region = region, InScope = inScope };
            locations[code] = loc;
            db.Locations.Add(loc);
        }
        await db.SaveChangesAsync();

        // ---- 2. Load golden-mapping.json ----
        var goldenPath = Path.Combine(basePath, "golden-mapping.json");
        if (!File.Exists(goldenPath))
            throw new FileNotFoundException($"Missing required seed file: {goldenPath}. Run `node docs/seed-data/build-final-mapping.js` first.");
        var goldenJson = await File.ReadAllTextAsync(goldenPath);
        var golden = JsonSerializer.Deserialize<GoldenMappingFile>(goldenJson)
            ?? throw new InvalidOperationException("Failed to parse golden-mapping.json");
        if (golden.version != ExpectedMappingVersion)
            throw new InvalidOperationException($"golden-mapping.json version mismatch. Expected {ExpectedMappingVersion}, got {golden.version}.");

        Console.WriteLine($"  Golden mapping: {golden.mappings.Count} (location × subprocess) entries, generated {golden.generatedAt}");

        // ---- 3. Subprocesses (from golden mapping) ----
        var subprocesses = new Dictionary<string, Subprocess>();
        var subOrderedNames = golden.mappings
            .Select(m => (m.subprocess, m.phase, m.globalSeq, m.scope, m.quarterly))
            .Distinct()
            .OrderBy(x => x.globalSeq)
            .ToList();
        foreach (var info in subOrderedNames)
        {
            if (subprocesses.ContainsKey(info.subprocess)) continue;
            var sub = new Subprocess
            {
                Name = info.subprocess,
                Phase = info.phase,
                DisplayOrder = info.globalSeq,
                Scope = info.scope,
                IsQuarterly = info.quarterly,
            };
            subprocesses[info.subprocess] = sub;
            db.Subprocesses.Add(sub);
        }
        await db.SaveChangesAsync();

        // ---- 4. LocationStepRegistry (mandatory steps per location+subprocess) ----
        var registryRows = 0;
        foreach (var m in golden.mappings)
        {
            if (!locations.TryGetValue(m.location, out var loc)) continue;
            if (!subprocesses.TryGetValue(m.subprocess, out var sub)) continue;
            for (var i = 0; i < m.steps.Count; i++)
            {
                db.LocationStepRegistry.Add(new LocationStepRegistry
                {
                    LocationId = loc.Id,
                    SubprocessId = sub.Id,
                    RequiredStepName = m.steps[i],
                    DisplayOrder = i,
                    IsMandatory = true,
                });
                registryRows++;
            }
        }
        await db.SaveChangesAsync();
        Console.WriteLine($"  LocationStepRegistry: {registryRows} mandatory step rows");

        // ---- 5. Log entries (4 months, pre-resolved subprocess in each row) ----
        var logPath = Path.Combine(basePath, "log-entries.json");
        var logJson = await File.ReadAllTextAsync(logPath);
        var logRecords = JsonSerializer.Deserialize<List<LogEntryJson>>(logJson) ?? [];
        Console.WriteLine($"  Loading {logRecords.Count} log entries across months...");

        // Create McpRun per distinct reportMonth
        var mcpRuns = new Dictionary<string, McpRun>();
        foreach (var rm in logRecords.Select(r => r.reportMonth).Distinct())
        {
            var year = 2000 + int.Parse(rm[..2]);
            var month = int.Parse(rm[2..]);
            var run = new McpRun
            {
                ReportMonth = rm,
                Year = year,
                Month = month,
                Status = "Completed",
                EomDate = new DateTime(year, month, DateTime.DaysInMonth(year, month)),
            };
            mcpRuns[rm] = run;
            db.McpRuns.Add(run);
        }
        await db.SaveChangesAsync();

        // Fill run start/end dates from log data
        foreach (var rm in mcpRuns.Keys)
        {
            var entries = logRecords.Where(r => r.reportMonth == rm).ToList();
            var starts = entries.Where(e => e.startedAt != null).Select(e => DateTime.Parse(e.startedAt!)).ToList();
            var ends = entries.Where(e => e.endedAt != null).Select(e => DateTime.Parse(e.endedAt!)).ToList();
            if (starts.Count > 0) mcpRuns[rm].StartDate = starts.Min();
            if (ends.Count > 0) mcpRuns[rm].EndDate = ends.Max();
        }
        await db.SaveChangesAsync();

        // Insert ProcessLogEntry rows in batches of 200
        var batch = new List<ProcessLogEntry>();
        foreach (var r in logRecords)
        {
            if (!locations.TryGetValue(r.location, out var loc)) continue;
            if (!mcpRuns.TryGetValue(r.reportMonth, out var run)) continue;

            batch.Add(new ProcessLogEntry
            {
                McpRunId = run.Id,
                LocationId = loc.Id,
                Process = r.process,
                ScriptName = r.scriptName,
                StepName = r.stepName,
                StateName = r.stateName,
                StartedAt = ParseNullableDate(r.startedAt),
                EndedAt = ParseNullableDate(r.endedAt),
                NextStarted = ParseNullableDate(r.nextStarted),
                StartMarker = r.startMarker,
                EndMarker = r.endMarker,
                Iteration = r.iteration,
                TotalRuntimeHours = r.totalRuntimeHours,
                FailedRuntimeHours = r.failedRuntimeHours,
                EfficientRuntimeHours = r.efficientRuntimeHours,
                OpportunityCostHours = r.opportunityCostHours,
                InefficientRuntimeHours = r.inefficientRuntimeHours,
                E2ERuntimeHours = r.e2eRuntimeHours,
                ErrorMessage = r.errorMessage,
            });
            if (batch.Count >= 200)
            {
                db.ProcessLogEntries.AddRange(batch);
                await db.SaveChangesAsync();
                batch.Clear();
            }
        }
        if (batch.Count > 0)
        {
            db.ProcessLogEntries.AddRange(batch);
            await db.SaveChangesAsync();
        }

        // ---- 6. SLA targets ----
        var slaPath = Path.Combine(basePath, "sla-targets.json");
        if (File.Exists(slaPath))
        {
            var slaJson = await File.ReadAllTextAsync(slaPath);
            var slaRecords = JsonSerializer.Deserialize<List<SlaEntryJson>>(slaJson) ?? [];
            Console.WriteLine($"  Loading {slaRecords.Count} SLA targets...");
            var slaInserted = 0;
            var slaDedupe = new HashSet<(int, int)>();
            foreach (var s in slaRecords)
            {
                if (!locations.TryGetValue(s.locationCode, out var loc)) continue;
                if (!subprocesses.TryGetValue(s.subprocessName, out var sub))
                {
                    // Unknown subprocess in SLA sheet; create a placeholder so the SLA row can be persisted
                    sub = new Subprocess { Name = s.subprocessName, Phase = "Processing", DisplayOrder = 99, Scope = "Location Specific" };
                    subprocesses[s.subprocessName] = sub;
                    db.Subprocesses.Add(sub);
                    await db.SaveChangesAsync();
                }
                var key = (loc.Id, sub.Id);
                if (!slaDedupe.Add(key)) continue; // unique constraint on (Location, Subprocess)
                db.SlaTargets.Add(new SlaTarget
                {
                    LocationId = loc.Id,
                    SubprocessId = sub.Id,
                    Frequency = s.frequency,
                    Deadline = s.deadline ?? "",
                    Workday = s.GetWorkday(),
                    SlaDate = ParseNullableDate(s.slaDate),
                });
                slaInserted++;
            }
            await db.SaveChangesAsync();
            Console.WriteLine($"  SLA targets inserted: {slaInserted} (deduped from {slaRecords.Count})");
        }

        // ---- 7. SubprocessRun matrix (derived from log entries using canonical-iteration rule) ----
        Console.WriteLine("  Building subprocess run matrix...");
        await BuildSubprocessRunMatrix(db, mcpRuns, locations, subprocesses, logRecords);

        Console.WriteLine("Seeding complete!");
    }

    private static async Task BuildSubprocessRunMatrix(
        GreenlightContext db,
        Dictionary<string, McpRun> mcpRuns,
        Dictionary<string, Location> locations,
        Dictionary<string, Subprocess> subprocesses,
        List<LogEntryJson> logRecords)
    {
        // Log entries now have `subprocess` pre-resolved by build-final-mapping.js — no prefix matching needed
        foreach (var (rm, run) in mcpRuns)
        {
            var runEntries = logRecords.Where(r => r.reportMonth == rm && !string.IsNullOrEmpty(r.subprocess)).ToList();
            var grouped = runEntries.GroupBy(x => new { x.location, Sub = x.subprocess! });

            foreach (var g in grouped)
            {
                if (!locations.TryGetValue(g.Key.location, out var loc)) continue;
                if (!subprocesses.TryGetValue(g.Key.Sub, out var sub)) continue;

                var entries = g.ToList();
                var latestIter = entries.Max(e => e.iteration);
                var latestEntries = entries.Where(e => e.iteration == latestIter).ToList();
                var status = DeriveStatus(latestEntries);

                var starts = entries.Where(e => e.startedAt != null).Select(e => DateTime.Parse(e.startedAt!));
                var ends = entries.Where(e => e.endedAt != null).Select(e => DateTime.Parse(e.endedAt!));
                var startedAt = starts.Any() ? starts.Min() : (DateTime?)null;
                var completedAt = ends.Any() ? ends.Max() : (DateTime?)null;
                var elapsed = (startedAt.HasValue && completedAt.HasValue)
                    ? (completedAt.Value - startedAt.Value).TotalMinutes : (double?)null;

                db.SubprocessRuns.Add(new SubprocessRun
                {
                    McpRunId = run.Id,
                    LocationId = loc.Id,
                    SubprocessId = sub.Id,
                    Status = status,
                    StartedAt = startedAt,
                    CompletedAt = completedAt,
                    ElapsedMinutes = elapsed,
                    CompletedSteps = latestEntries.Count(e => e.stateName == "Completed"),
                    TotalRequiredSteps = latestEntries.Count,
                });
            }
        }
        await db.SaveChangesAsync();
    }

    private static string DeriveStatus(List<LogEntryJson> entries)
    {
        if (entries.Any(e => e.stateName is "Failed" or "Unfinished")) return "Failed";
        if (entries.Any(e => e.stateName == "Stopped")) return "Stopped";
        if (entries.All(e => e.stateName == "Completed")) return "Completed";
        return "Running";
    }

    private static DateTime? ParseNullableDate(string? s)
    {
        if (string.IsNullOrEmpty(s)) return null;
        return DateTime.TryParse(s, out var d) ? d : null;
    }

    // ---------- JSON DTOs ----------

    private class GoldenMappingFile
    {
        public string version { get; set; } = "";
        public string generatedAt { get; set; } = "";
        public int totalLocations { get; set; }
        public int totalSubprocesses { get; set; }
        public List<GoldenMappingEntry> mappings { get; set; } = [];
    }

    private class GoldenMappingEntry
    {
        public string location { get; set; } = "";
        public string subprocess { get; set; } = "";
        public string phase { get; set; } = "";
        public string phaseDisplay { get; set; } = "";
        public string scope { get; set; } = "";
        public bool quarterly { get; set; }
        public int globalSeq { get; set; }
        public double avgRank { get; set; }
        public List<string> steps { get; set; } = [];
        public List<string> scripts { get; set; } = [];
        public List<string> monthsSeen { get; set; } = [];
    }

    private class LogEntryJson
    {
        public string reportMonth { get; set; } = "";
        public string location { get; set; } = "";
        public string process { get; set; } = "";
        public string? startMarker { get; set; }
        public string? endMarker { get; set; }
        public string? startedAt { get; set; }
        public string? endedAt { get; set; }
        public string? nextStarted { get; set; }
        public string? errorMessage { get; set; }
        public string stateName { get; set; } = "";
        public string scriptName { get; set; } = "";
        public int iteration { get; set; } = 1;
        public string stepName { get; set; } = "";
        public double totalRuntimeHours { get; set; }
        public double failedRuntimeHours { get; set; }
        public double efficientRuntimeHours { get; set; }
        public double opportunityCostHours { get; set; }
        public double inefficientRuntimeHours { get; set; }
        public double e2eRuntimeHours { get; set; }
        public string? subprocess { get; set; }  // pre-resolved by JS tool
        public string? phase { get; set; }
    }

    private class SlaEntryJson
    {
        public string locationShort { get; set; } = "";
        public string locationCode { get; set; } = "";
        public string subprocessName { get; set; } = "";
        public string frequency { get; set; } = "";
        public string deadline { get; set; } = "";
        public object? workday { get; set; }
        public string? slaDate { get; set; }

        public int GetWorkday()
        {
            if (workday is JsonElement je)
            {
                if (je.ValueKind == JsonValueKind.Number) return je.GetInt32();
                if (je.ValueKind == JsonValueKind.String && int.TryParse(je.GetString(), out var v)) return v;
            }
            if (workday is int i) return i;
            if (workday is string s && int.TryParse(s, out var w)) return w;
            return 0;
        }
    }
}
